[package]
name = "no_std_test_lib"
version = "0.1.0"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
edition = "2018"

[dependencies]
rand_core = { version = "0.3", default-features = false }
curve25519-dalek = { version = "1.1", default-features = false, features = ["u32_backend"] }

